services:
  casino1:
    build:
      context: ./services/casino1
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    init: true

  admin:
    build:
      context: ./services/admin
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    init: true

  nginx:
    build:
      context: ./services/nginx
    volumes:
      - frontpages:/var/www/nginx:ro
    ports:
      - "80:80"
    init: true

  sftp:
    build:
      context: ./services/sftp
    volumes:
      - frontpages:/home
    command: designer:pass:1001
    ports:
      - "2222:22"
    init: true

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  frontpages: 
  postgres_data: 